controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

set_users:
    path: /api/users
    methods: POST
    controller: App\Controller\UserController::store

get_users:
    path: /api/users
    methods: GET
    controller: App\Controller\UserController::index

get_users_by_id:
    path: /api/users/{id}
    methods: GET
    controller: App\Controller\UserController::show
